// Generated by typings
// Source: https://raw.githubusercontent.com/types/npm-invariant/58403cee078ebef52112c4227c4d23a97821ef5c/invariant.d.ts
declare module 'invariant' {
function invariant (condition: boolean, message: string, ...args: string[]): void;

export = invariant;
}
