export const ACTIONS = {
  RECEIVED_NOTIFICATIONS: 'RECEIVED_NOTIFICATIONS',
  NOTIFICATIONS_REQUEST_ERROR: 'NOTIFICATIONS_REQUEST_ERROR',
  NOTIFICATIONS_DRAWER_TOGGLE: 'NOTIFICATIONS_DRAWER_TOGGLE',
  NOTIFICATIONS_EXPAND_DRAWER_TAB: 'NOTIFICATIONS_EXPAND_DRAWER_TAB',
  NOTIFICATIONS_MARK_AS_READ: 'NOTIFICATIONS_MARK_AS_READ',
  NOTIFICATIONS_MARKED_AS_READ: 'NOTIFICATIONS_MARKED_AS_READ',
  NOTIFICATIONS_SET_REQUEST_STATUS: 'NOTIFICATIONS_SET_REQUEST_STATUS'
};

export const STATUS = {
  PENDING: 'PENDING',
  RESOLVED: 'RESOLVED',
  ERROR: 'ERROR'
};

export const ICON_CSS = {
  ok: 'pficon pficon-ok',
  success: 'pficon pficon-ok',
  info: 'pficon pficon-info',
  warning: 'pficon pficon-warning-triangle-o',
  error: 'pficon pficon-error-circle-o'
};
